# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
            ],
            options={
                'verbose_name': 'Album di Immagini',
                'verbose_name_plural': 'Album di Immagini',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
            ],
            options={
                'verbose_name': 'Galleria',
                'verbose_name_plural': 'Gallerie',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/images/gallery')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Album')),
            ],
            options={
                'verbose_name': 'Immagine',
                'verbose_name_plural': 'Immagini',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'Macchina',
                'verbose_name_plural': 'Macchine',
            },
        ),
        migrations.CreateModel(
            name='MachineImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/machine_images')),
                ('name', models.CharField(max_length=200)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Machine')),
            ],
            options={
                'verbose_name': 'Immagine per Macchina',
                'verbose_name_plural': 'Immagini per Macchina',
            },
        ),
        migrations.CreateModel(
            name='Paragraphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('site_description', models.TextField()),
                ('site_bio', models.TextField()),
                ('header_image', models.ImageField(upload_to='uploads/images/paragraphs')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('piva', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Gruppo di Descrizioni e Paragrafi del Sito',
                'verbose_name_plural': 'Gruppi di Descrizioni e Paragrafi del Sito',
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo di Lavorazione',
                'verbose_name_plural': 'Tipi di Lavorazione',
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='WorkCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.WorkCategory'),
        ),
        migrations.AddField(
            model_name='album',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Gallery'),
        ),
    ]
