# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='WorkCategory',
            new_name='work_category',
        ),
        migrations.AddField(
            model_name='paragraphs',
            name='fresatura_description',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paragraphs',
            name='fresatura_image',
            field=models.ImageField(default='Test', upload_to='uploads/images/paragraphs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paragraphs',
            name='gallery_image',
            field=models.ImageField(default='Test', upload_to='uploads/images/paragraphs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paragraphs',
            name='tornitura_description',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paragraphs',
            name='tornitura_image',
            field=models.ImageField(default='Test', upload_to='uploads/images/paragraphs'),
            preserve_default=False,
        ),
    ]
